language: node_js
node_js:
- '9'
before_install:
- cd massage-booking-system-frontend
- npm install
- CI=false npm run build
install:
- mv build ../massage-booking-system-backend
- cd ../massage-booking-system-backend
- npm install
- npm test
deploy:
  provider: heroku
  api_key:
    secure: yAqCKDokAYx5ycpnIQaJpLPbTAA2A3sAlFJEcvtYuC2XTFA5H6zMBae4vzA+SI5jpFTGCG8C8pu6SE8O/piS4eTgcM9Ke3te5MR4sTgBqWpsqnwnJ/C+wkOziHnR62BBGgOUG/jDJVLTD7WM3STHn6qBYUJ8Gs4XIIeRA9AVFIjg181URjDxuayT+ccQR047VtN9X75Ad0Qu1Ct8ErDRUXs4SEyHJVi9CRqJ7A1hTIQsZOc5Is1Vvcw1ATsY/H/FODveegkstnI7lB4G8acw+0FYJxcUe1OtKOtB/BVFkicq/ajQDznNdVkYnr41f6RX8VRYiJz3QrDDuTDoxm1q3QfNuGdUX3zLKlGkXCGh/VhO5d3zUTZbRt8BswuCv+7uvOA8ki9nHtYtBESismb3DrKVwB80zeutpauLCW09HPhF22aVFAlUWVP6dqqzGyHd4wqR1Rzd72dFwrxR6Z96B2unPlky+3Ho/QvT7xs4bQ4iJiSEq+58sotsrGoMqF/RlL9ziJik5v5Edy1jnACQG8fURGwN659QijD7DoynrgJNxYtZ0Q7A9HLIapeVYKxRxmLSwPnkrh6XMWxqa9YRwroe9m0X1L5TqzgKncFr+no7XYWizaRxIhiAn9cCYYD2HU68ItVvLwZpMnR/VQJocp5WYHrKK2B6GCuApXFJLqg=
  app: massage-booking-system
  on:
    repo: karoliinaemilia/massage-booking-system
